### ISSUE TITLE
想问下投放音乐怎么做

### ISSUE THREAD

**Issue by fujingxie** [zaneCC/AndroidUPnPDemo#1]
最近有个任务是在把盒子端的音乐投放到音响的，请问下这个要怎么做

**Comment by zaneCC** [comment]
音乐的话 它就格式跟视频不同而已，可以看一下格式：

//支持的媒体格式 DMR支持的媒体格式。根据DLNA的描述排列多个媒体格式。
protocolInfo="http-get:*:audio/mpeg:*;http-get:*:audio/wav:;http-get:*:audio/x-ms-wma:*;http-get:*:video/mp4:*;http-get:*:video/mpeg:*;http-get:*:video/mpeg2:*;http-get:*:video/avi:*;http-get:*:image/gif:*;http-get:*:image/jpeg:*;http-get:*:image/png:*;http-get:*:mpeg4:*;rtsp-rtp-udp:*:mpeg4/h.264:*;x-ctc_videophone_receive,rtp_udp:50500,50343:video/h.264:*"
--

protocolInfo  《－该字段就可以设置格式 
<res protocolInfo="http-get:*:*/*:*"  >url</res>
"http-get:*:*/*:*"： 这个就代表所有的类型。
你可以试试。
