### ISSUE TITLE
从DLNA库类下回来的Cling总是mvn clean package失败...

### ISSUE THREAD

**Issue by AnnaClancy** [zaneCC/AndroidUPnPDemo#2]
QAQ姐姐你是怎么把cling包导入自己的工程的啊

**Comment by zaneCC** [comment]
解决了吗？

**Comment by zaneCC** [comment]
在工程级 build.gradle 添加：
buildscript {
...
    repositories {
        jcenter()
        mavenCentral()
        maven {
            url 'http://4thline.org/m2'
        }
    }
...
}
allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            url 'http://4thline.org/m2'
        }
    }
}

在 app级  build.gradle 添加：
android{
...
packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/beans.xml'
    }
...
}

dependencies {
    ...
    // Cling library
    compile 'org.fourthline.cling:cling-core:2.1.1'
    compile 'org.fourthline.cling:cling-support:2.1.1'
    // Jetty library
    compile 'org.eclipse.jetty:jetty-server:8.1.12.v20130726'
    compile 'org.eclipse.jetty:jetty-servlet:8.1.12.v20130726'
    compile 'org.eclipse.jetty:jetty-client:8.1.12.v20130726'
    compile 'org.slf4j:slf4j-simple:1.7.21'
    compile 'com.koushikdutta.urlimageviewhelper:urlimageviewhelper:1.0.4'

...
}

**Comment by zaneCC** [comment]
解决了吗？

**Comment by AnnaClancy** [comment]
上午把工程级build.gradle中全添加好了+app级里的[Cling library]的部分，发现可以直接调用函数！就很开心地跑去翻译姐姐的代码了！>v<

OvO刚刚看到邮件！
往app级里build.gradle加了其他代码，Sync Now后manifest报错！但报错的不是main里的manifest，是一个debug文件夹里的xml文件.....

报错内容是对manifest xmlns: android = ...（也就是xml文件中最开始的内容）这一行
报错类型是：URI is not registered (Settings | Languages & Frameworks | Schemas and DTDs)

查了一会

不、不明白，可我manifests里的xml文件好好的啊...这个debug里的xml是在干嘛... (/ __ \ )

**Comment by zaneCC** [comment]
要么你clean一下。或者 rebuild一下。 哈哈。 如果还不行 你把你 manifest 贴一份

**Comment by AnnaClancy** [comment]
哇你还笑！！！（超委屈）clean与rebuild都用过！！！(/_\) 查的时候就做过了.....
manifest本身没问题，它的复件（一模一样）报错而已。
如果不是什么大问题我不想折腾它了...好累。_(qwq / \)_

**Comment by zaneCC** [comment]
好好好 我不笑。， 你看一下这个能不能帮到你：https://stackoverflow.com/questions/17511254/android-studio-error-parsing-xml-uri-is-not-registered

**Comment by AnnaClancy** [comment]
好——

**Comment by AnnaClancy** [comment]
解决啦！
File ->  Settings  -> schemas and DtDs，把报错的路径拷贝了加进Ignored Schemas and DTDs就不报错了。

然后发现下面service、android:allowBackup等等等红色报错不是联动的= =
报错类型：Attribute androd:versionCode is not allowed here
？？？
clean&rebuild先走一遍！日常没用！
我去查资料了......

> Just Close your manifest file and reopen it. It worked for me.

？？？
可这个报错的xml根本就不是我app里mannifests的xml！
rebuild出错的永远是debug\AndroidManifest.xml
我app里的xml可乖了才没有报错！

> For your "attribute not allowed here" problem, versionCode, versionName have to be placed in the build.gradle file and not in the Android Manifest. That should solve the problem
> 
> UpDate :
> remove this line from manifest.xml file.
> android:versionCode="1"
> android:versionName="1.0"

......app\src\main\AndroidManifest.xml早就没有这两行了。
debug\AndroidManifest.xml里也试过了，没有用。

**我不想管你这个debug\AndroidManifest.xml了！！QAQ**

**Comment by AnnaClancy** [comment]
**确定是因为**

> 在 manifest 里面定义这个 Service
> <service android:name="org.fourthline.cling.android.AndroidUpnpServiceImpl"/>

导致的问题

但不要问我为什么因为我肯定不知道！= =

**Comment by zaneCC** [comment]
没问题我就close了啊
